version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: x86
before_build:
- cmd: >-
    git submodule init

    git submodule update

    mkdir build

    cd build


    set THR_CMAKE_BOOST_CONFIG=-DBOOST_INCLUDE_DIR=C:\Libraries\boost_1_66_0 -DBOOST_LIB_DIR=C:\Libraries\boost_1_66_0\lib32-msvc-14.1

    set THR_CMAKE_CONFIG=-DCMAKE_INSTALL_PREFIX=../install-2017 -G "Visual Studio 15 2017"


    cmake ../ %THR_CMAKE_BOOST_CONFIG% %THR_CMAKE_CONFIG%
build:
  project: build\INSTALL.vcxproj
  parallel: true
  verbosity: minimal
artifacts:
- path: .\install-2017
  name: THRotator-${APPVEYOR_REPO_COMMIT}